# Generated by Django 2.2.7 on 2019-12-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_apt_unit_no', models.CharField(max_length=20)),
                ('descriptor', models.CharField(max_length=100, null=True)),
                ('street_no', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_prov', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('formation_date', models.DateField(verbose_name='Band formation')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyr.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_start', models.DateField(null=True, verbose_name='Event Date')),
                ('duration_description', models.CharField(max_length=100, null=True)),
                ('bands', models.ManyToManyField(to='fyr.Band')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyr.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='BandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('band', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fyr.Band')),
            ],
        ),
    ]
