# Generated by Django 2.2.7 on 2019-12-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='venues',
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyr.Venue'),
        ),
    ]
