# Generated by Django 2.2.7 on 2019-12-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyr', '0002_auto_20191130_2208'),
    ]

    operations = [
        migrations.RenameModel('Events', 'Event')
    ]
