# Generated by Django 2.2.7 on 2019-12-05 02:44

from django.db import migrations, models
import datetime
from django.db import transaction, IntegrityError

def reformat_band_formation(apps, schema_editor):
    Band = apps.get_model('fyr', 'Band')
    for band in Band.objects.all():
        try:
            with transaction.atomic():
                band.formation_date = datetime.date.today()
                band.save()
        except IntegrityError:
            band.delete()

    Event = apps.get_model('fyr', 'Event')
    for event in Event.objects.all():
        try:
            with transaction.atomic():
                event.event_start = datetime.date.today()
                event.save()
        except IntegrityError:
            event.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fyr', '0003_auto_20191201_2254'),
    ]

    operations = [
        migrations.RunPython(reformat_band_formation),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='band',
            name='formation_date',
            field=models.DateField(null=True, verbose_name='Band formation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),

    ]
