# Generated by Django 2.2.7 on 2019-12-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyr', '0004_auto_20191204_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='formation_date',
            field=models.DateField(default='1897-10-11', verbose_name='Band formation'),
            preserve_default=False,
        ),
    ]
